routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'BlogController@index');
// Route::get('/', 'InfoController@index');
// Route::get('/', function () {
    //     return view('welcome');
    // });
    // Route::get('/home', function () {
        //     return view('home');
        // })->name('home');
        // Route::get('/', function() {
            //   return view('layout.home');
            // });
            
            // BERITA TERBARU
            Route::get('/isi_post/{slug}', 'BlogController@isi_post')->name('blog.isi_post');
            Route::get('/list_post', 'BlogController@list_post')->name('blog.list_post');
            Route::get('/category/{category}', 'BlogController@list_category')->name('blog.category');
            Route::get('/cari', 'BlogController@cari')->name('blog.cari');
            

// Pengumuman Terbaru
Route::get('/isi_news/{slug}', 'InfoController@isi_news')->name('info.isi_news');
Route::get('/list_news', 'InfoController@list_news')->name('info.list_news');
Route::get('/category/{category}', 'InfoController@list_category')->name('info.category');

// dosen
Route::get('/list_dosens', 'RuangdosenController@list_dosens')->name('dosens.list_dosens');

Route::get('/list_komunikasi', 'KomunikasiController@list_komunikasi')->name('komunikasi.list_komunikasi');
Route::get('/isi_komunikasi', 'KomunikasiController@isi_komunikasi')->name('komunikasi.isi_komunikasi');

Route::get('/isi_d3', 'D3Controller@isi_d3')->name('d3.isi_d3');

Route::get('/isi_akre', 'AkreditasiController@isi_akre')->name('akreditasi.isi_akre');
Route::get('/list_akre', 'AkreditasiController@list_akre')->name('akreditasi.list_akre');

Route::get('/isi_sejarah', 'SejarahController@isi_sejarah')->name('sejarah.isi_sejarah');

Route::get('/isi_visimisi', 'VisimisiController@isi_visimisi')->name('visimisi.isi_visimisi');



Route::get('/stikomtv', function() {
    return view('layout.stikomtv');
  });

Route::get('/ijin', function() {
    return view('layout.ijin');
  });
  
  Route::group(['middleware' => 'auth'], function(){
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/category', 'CategoryController');
    Route::resource('/tag', 'TagController');
    Route::resource('/communications', 'CommunicationsController')->middleware('role: 1');
    Route::resource('/advertisings', 'AdvertisingsController')->middleware('role: 1');
    Route::resource('/dosens', 'DosensController')->middleware('role: 1');
    Route::resource('/akreditations', 'AkreditationsController')->middleware('role: 1');
    Route::resource('/histories', 'HistoriesController')->middleware('role: 1');
    Route::resource('/visimisions', 'VisimisionsController')->middleware('role: 1');
    Route::resource('/post', 'PostController')->middleware('role: 1');
    Route::resource('/news', 'NewsController')->middleware('role: 0');
    Route::resource('/user', 'UserController');
    
});
// Route::get('laporan-pdf', 'PdfController@pdf');

app/Http/Controllers/HistoriesController.php
<?php

namespace App\Http\Controllers;

use App\Histories;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class HistoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $histories = Histories::paginate(10);
        return view('admin.histories.index', compact('histories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.histories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'keterangan' => 'required',
            'gambar' => 'required'
        ]);

        $gambar = $request->gambar;
        $new_gambar = time().$gambar->getClientOriginalName();

        $histories = Histories::create([
            'name' => $request->name,
            'keterangan' => $request->keterangan,
            'gambar' => 'public/uploads/profile/histories/'.$new_gambar,
            'slug' => Str::slug($request->name)
        ]);
        
        $gambar->move('public/uploads/profile/histories/', $new_gambar);
        return redirect()->route('histories.index')->with('success', 'Data Berhasil Disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $histories = Histories::findorfail($id);
        return view('admin.histories.edit', compact('histories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'keterangan' => 'required',
            // 'gambar' => 'required'
        ]);
        $histories = Histories::findorfail($id);
        if ($request->has('gambar')) {
            $gambar = $request->gambar;
            $new_gambar = time().$gambar->getClientOriginalName();
            $gambar->move('public/uploads/profile/histories/', $new_gambar);

            $histories_data = [
                'name' => $request->name,
                'keterangan' => $request->keterangan,
                'gambar' => 'public/uploads/profile/histories/'.$new_gambar,
                'slug' => Str::slug($request->judul)
            ];    
        }
        else{
            $histories_data = [
                'name' => $request->name,
                'keterangan' => $request->keterangan,
                'slug' => Str::slug($request->judul)
            ];
     
        }
        
        $histories->update($histories_data);

        return redirect()->route('histories.index')->with('success', 'Data Berhasil Di Update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $histories = Histories::findorfail($id);
        $histories->delete();

        return redirect()->back()->with('success', 'Data Berhasil Dihapus');
    }
}

resources/views/admin/histories/create.blade.php
@extends('backend.home')
@section('sub-judul', 'Tambah Histories')
@section('content')

    @if(count($errors)>0)
        @foreach($errors->all() as $error)
        <div class="alert alert-danger" role="alert">
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ Session('success') }}
    </div>
    @endif

<form action="{{ route('histories.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="form-group">
        <label for="formGroupExampleInput" name="name">Judul</label>
        <input type="text" class="form-control" id="formGroupExampleInput" name="name" placeholder="Masukkan Judul">
    </div>
    <div class="form-group">
        <label>Sejarah</label>
        <textarea name="keterangan" id="editor" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label>Thumbnails</label>
        <input type="file" name="gambar" class="form-control">
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-block">Simpan Histories</button>
    </div>
    </form>
<script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
<script>
	ClassicEditor
		.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
@endsection

resources/views/admin/histories/edit.blade.php
@extends('backend.home')
@section('sub-judul', 'Edit Histories')
@section('content')

    @if(count($errors)>0)
        @foreach($errors->all() as $error)
        <div class="alert alert-danger" role="alert">
            {{ $error }}
        </div>
        @endforeach
    @endif

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ Session('success') }}
    </div>
    @endif

    <form action="{{ route('histories.update', $histories->id ) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('PATCH')
    <div class="form-group">
        <label for="formGroupExampleInput" name="name">Judul</label>
        <input type="text" class="form-control" id="formGroupExampleInput" name="name" value="{{ $histories->name }}">
    </div>
    <div class="form-group">
        <label>Sejarah</label>
        <textarea name="keterangan" id="editor" class="form-control">{{ $histories->keterangan }}</textarea>
    </div>
    <div class="form-group">
        <label>Thumbnails</label>
        <input type="file" name="gambar" class="form-control">
    </div>
    <div class="form-group">
        <button class="btn btn-primary btn-block">Simpan Histories</button>
    </div>
    </form>
<script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
<script>
	ClassicEditor
		.create( document.querySelector( '#editor' ) )
		.then( editor => {
			window.editor = editor;
		} )
		.catch( err => {
			console.error( err.stack );
		} );
</script>
@endsection

resources/views/admin/histories/index.blade.php
@extends('backend.home')
@section('title', 'Histories')
@section('content')

    @if(Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ Session('success') }}
    </div>
    @endif

    <a href="{{ route('histories.create') }}" class="btn btn-info btn-sm">Tambah Histories</a>
    <br><br>
    <table class="table table-striped table-hover table-sm table-bordered text-center">
        <thead>
            <tr>
                <th>No</th>
                <th>Judul</th>
                <th>Gambar</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach ($histories as $result => $hasil)
            <tr>
                <td>{{ $result + $histories->firstitem() }}</td>
                <td>{{ $hasil->name }}</td>
                <td><img src="{{ asset($hasil->gambar) }}" class="img-fluid" style="width:80px"></td>
                <td>
                    <form action="{{ route('histories.destroy', $hasil->id) }}" method="POST">
                        @csrf
                        @method('delete')
                        <a href="{{ route('histories.edit', $hasil->id) }}" class="btn btn-sm btn-primary">Edit</a>
                        &nbsp
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
@endsection